### ISSUE TITLE
Div by zero exception

### ISSUE THREAD

**Issue by erocs** [gmlaxfanatic/ItemExchange#101]
2014-01-06 16:46:48 [SEVERE] Could not pass event PlayerInteractEvent to ItemExchange v0.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:478)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:463)
        at org.bukkit.craftbukkit.v1_6_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:207)
        at net.minecraft.server.v1_6_R3.PlayerInteractManager.dig(PlayerInteractManager.java:108)
        at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:540)
        at net.minecraft.server.v1_6_R3.Packet14BlockDig.handle(SourceFile:46)
        at org.spigotmc.netty.NettyNetworkManager.b(NettyNetworkManager.java:230)
        at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:117)
        at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
        at org.spigotmc.netty.NettyServerConnection.b(NettyServerConnection.java:132)
        at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:594)
        at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:240)
        at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:483)
        at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:415)
        at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)
Caused by: java.lang.ArithmeticException: / by zero
        at com.untamedears.ItemExchange.utility.ExchangeRule.checkMultiples(ExchangeRule.java:529)
        at com.untamedears.ItemExchange.utility.ItemExchange.messagePlayer(ItemExchange.java:368)
        at com.untamedears.ItemExchange.utility.ItemExchange.playerResponse(ItemExchange.java:274)
        at com.untamedears.ItemExchange.listeners.ItemExchangeListener.playerInteractionEvent(ItemExchangeListener.java:62)
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 17 more

**Comment by erocs** [comment]
Fixed 3c5c4dcf08
